#!/usr/bin/env bash
#this is a script to make me really mad 

i=1
while [ "$i" -le 100 ]
do
		fizz=$((i%3))
		buzz=$((i%5))
		if [ $fizz = 0 ] && [ $buzz = 0 ]
		then
			echo "FizzBuzz"
		elif [ $fizz = 0 ]
		then
			echo "Fizz"
		elif [ $buzz = 0 ]
		then
			echo "Buzz"
		else
			echo "$i"
		fi
	((i++))
done
