#!/usr/bin/env bash
#this is a script to make me really mad 

i=1
fizz=$((i%3))
buzz=$((i%5))
while [ "$i" -le 100 ]
do
		if [[ "$i" = "${fizz[*]}" ]]  && [[ "$i" = "${buzz[*]}" ]]
		then
			echo "FizzBuzz"
		elif [[ "$i" = "${fizz[*]}" ]]
		then
			echo "Fizz"
		elif [[ "$i" = "${buzz[*]}" ]]
		then
			echo "Buzz"
		else
			echo "$i"
		fi
	((i++))
done
